-- Used to automatically generate UUIDs for new Categories
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- The user's uuid is not autogenerated because it is created somewhere else (auth microservice)
CREATE TABLE "User" (
  "id" uuid PRIMARY KEY,
  "name" varchar NOT NULL,
  "profilePic" BYTEA USING decode("profilePic", "escape")
);

CREATE TABLE "UserInterests" (
  "user_id" uuid,
  "interest_id" uuid,
  PRIMARY KEY ("user_id", "interest_id")
);

-- I had to add a table for Categories because UserInterests references it
CREATE TABLE "Category" (
  "id" uuid PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "category" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp DEFAULT null
);

ALTER TABLE "UserInterests" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "UserInterests" ADD FOREIGN KEY ("interest_id") REFERENCES "Category" ("id");