-- Used to automatically generate UUIDs for new Categories
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- The user's uuid is not autogenerated because it is created somewhere else (auth microservice)
CREATE TABLE "User" (
  "id" uuid PRIMARY KEY,
  "name" varchar NOT NULL,
  "profilePic" BYTEA
);

CREATE TABLE "UserInterests" (
  "user_id" uuid,
  "interest_id" uuid,
  PRIMARY KEY ("user_id", "interest_id")
);

ALTER TABLE "UserInterests" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");